## __Collaborative Filtering Recommendation System__

In [64]:
import pandas as pd

In [65]:
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
ratings.head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [66]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [67]:
ratings = pd.merge(movies, ratings).drop(['genres','timestamp'], axis=1)
ratings.head()

   movieId             title  userId  rating
0        1  Toy Story (1995)       2     5.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       8     5.0
3        1  Toy Story (1995)      11     4.0
4        1  Toy Story (1995)      14     4.0

In [68]:
user_ratings = ratings.pivot_table(index=['userId'],
                                   columns=['title'], 
                                  values='rating')
user_ratings.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...And Justice for All (1979),10 (1979),...,[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),a/k/a Tommy Chong (2005),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
# Filling missing value with 0
user_ratings = user_ratings.fillna(0)
user_ratings

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...And Justice for All (1979),10 (1979),...,[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),a/k/a Tommy Chong (2005),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,0.0,0.0,2.5,0.0,0.0,0.0,2.0,0.0,3.0,2.5,...,0.0,1.5,0.5,0.0,2.0,0.0,3.5,0.0,2.0,3.0

In [70]:
# similarity matrix => using correlation
item_similarity_df = user_ratings.corr()
item_similarity_df.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...And Justice for All (1979),10 (1979),...,[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),a/k/a Tommy Chong (2005),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.000000,-0.001499,-0.001499,-0.002548,-0.006581,-0.001499,-0.009078,-0.004886,0.340758,-0.002451,...,-0.003917,-0.002733,-0.001697,-0.001499,-0.007851,-0.001499,0.154004,-0.003624,0.091972,-0.001499
'Hellboy': The Seeds of Creation (2004),-0.001499,1.000000,-0.001499,-0.002548,-0.006581,-0.001499,-0.009078,-0.004886,-0.004719,-0.002451,...,-0.003917,-0.002733,-0.001697,-0.001499,-0.007851,-0.001499,-0.006838,-0.003624,0.142516,-0.001499
'Round Midnight (1986),-0.001499,-0.001499,1.000000,-0.002548,-0.006581,-0.001499,0.074277,-0.004886,0.254388,0.679836,...,-0.003917,0.225433,0.139967,-0.001499,0.094484,-0.001499,0.218341,-0.003624,0.091972,1.000000
'Til There Was You (1997),-0.002548,-0.002548,-0.002548,1.000000,-0.011185,-0.002548,-0.015428,-0.008303,-0.008020,-0.004166,...,-0.006657,-0.004644,-0.002883,-0.002548,-0.013343,-0.002548,-0.011621,-0.006158,-0.015495,-0.002548
"'burbs, The (1989)",-0.006581,-0.006581,-0.006581,-0.011185,1.000000,-0.006581,-0.006918,0.215640,0.082411,-0.010761,...,0.041282,-0.011995,-0.007448,-0.006581,0.185659,-0.006581,0.077304,-0.015908,0.128605,-0.006581

In [71]:
def get_similar_movies(movie_name, user_rating):
    similar_score = item_similarity_df[movie_name] * (user_rating-2.5)
    similar_score = similar_score.sort_values(ascending=False)
    
    return similar_score

In [77]:
user_favorite = [('Being Flynn (2012)', 5)]

similar_movies = pd.DataFrame()

for movie, rating in user_favorite:
    similar_movies = similar_movies.append(
        get_similar_movies(movie, rating), ignore_index=True)
    
print('Rekomendasi Film untuk Widodo:')
similar_movies.sum().sort_values(ascending=False).head()

Rekomendasi Film untuk Widodo:

Dawn Patrol, The (1938)         2.5
Glass Key, The (1942)           2.5
Tale of Two Cities, A (1935)    2.5
In Darkness (2011)              2.5
Too Big to Fail (2011)          2.5
dtype: float64